version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - REPOSITORY_URI=699260652768.dkr.ecr.eu-central-1.amazonaws.com/taxi-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo build Docker image on `date`
      - echo building docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest:latest $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
